# Generated by Django 4.1.5 on 2023-02-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypesOfServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField(null=True)),
                ('category', models.CharField(choices=[("Men's haircut", "Men's haircut"), ("Women's haircut", "Women's haicut"), ("Children's haircut", 'Детская  стрижка')], max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
