# Generated by Django 4.1.5 on 2023-02-26 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_typesofservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='typesofservices',
            name='category',
            field=models.CharField(choices=[("Men's haircut", 'Мужская стрижка'), ("Women's haircut", 'Женская стрижка'), ("Children's haircut", 'Детская  стрижка')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('В ожиданий', 'В ожиданий'), ('Выполнено', 'Выполнено')], max_length=200, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.customuser')),
                ('type_of_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.typesofservices')),
            ],
        ),
        migrations.AddField(
            model_name='typesofservices',
            name='tags',
            field=models.ManyToManyField(to='main.tag'),
        ),
    ]
