# Generated by Django 4.1.5 on 2023-02-06 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_dayofweek_rest_workinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Обед'),
        ),
        migrations.CreateModel(
            name='MasterShadow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dayofweek', verbose_name='День недели')),
                ('rest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rest', verbose_name='Обед')),
                ('working_hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.workinghours', verbose_name='Время работы')),
            ],
        ),
    ]
